version: '3.2'
services:
  postgres:
    image: postgres
    ports:
    - "5432:5432"
    container_name: postgres
    env_file:
    - ./.npmrc.dev
  redis:
    image: redis
    ports:
    - "6379:6379"
    container_name: redis    