version: 2
jobs:
  build:
    working_directory: ~/overhide-social
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          shell: /bin/sh
          command: |
            printf "DEBUG=overhide-social*\n" > .npmrc.dev;
            printf "POSTGRES_HOST=postgres\n" >> .npmrc.dev;
            printf "POSTGRES_PORT=5432\n" >> .npmrc.dev;
            printf "POSTGRES_DB=oh-social\n" >> .npmrc.dev;
            printf "POSTGRES_USER=adam\n" >> .npmrc.dev;
            printf "POSTGRES_PASSWORD=c0c0nut\n" >> .npmrc.dev;
            printf "KEYV_URI=redis://redis:6379\n" >> .npmrc.dev;
            printf "SALT=salt\n" >> .npmrc.dev;
            printf "INTERNAL_TOKEN=fake\n" >> .npmrc.dev;
            printf "AUTH_TOKEN_URL={\"microsoft\": \"https://token\", \"google\": \"https://token\"}\n" >> .npmrc.dev;
            printf "AUTH_CLIENT_ID=fake\n" >> .npmrc.dev;
            printf "AUTH_CLIENT_SECRET=fake\n" >> .npmrc.dev;
            printf "AUTH_REDIRECT_URI=https://localhost:8120/redirect\n" >> .npmrc.dev;
            cat .npmrc.dev   
      - run:
          shell: /bin/sh
          command: docker-compose -f main/docker/docker-compose.yml -f main/docker/docker-compose.dev.yml --project-directory . --project-name oh up -d 
      - run:
          shell: /bin/sh
          command: docker exec `docker ps -q --filter name="oh-social"` npm run db-evolve
      - run:
          shell: /bin/sh
          command: docker exec `docker ps -q --filter name="oh-social"` npm run test-report
      - store_test_results:
          path: ./test-report
      - store_artifacts:
          path: ./test-report